# File: preempt_consts.py
#
# Copyright (c) 2019-2021 Splunk Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions
# and limitations under the License.
#
#
# Define your constants here
ATTRIBUTE_TYPES = {
    'samAccountName': 'samAccountNames',
    'primaryDisplayName': 'primaryDisplayNames',
    'secondaryDisplayName': 'secondaryDisplayNames'
}

TIMELINE_EVENT_TYPES = "[SUCCESSFUL_AUTHENTICATION, FAILED_AUTHENTICATION, SERVICE_ACCESS, DCERPC_OPERATION, REMOTE_CODE_EXECUTION, \
    FILE_OPERATION, LDAP_SEARCH, ACCOUNT_CREATED, PASSWORD_CHANGE, ACCOUNT_NAME_CHANGE, DEPARTMENT_CHANGE, OU_CHANGE, EMAIL_ADDRESS_CHANGE, \
    ACCOUNT_ENABLED, ACCOUNT_DISABLED, ACCOUNT_LOCKED, ACCOUNT_UNLOCKED, ENTITY_RESURGENCE, ENTITY_INACTIVE, ENTITY_STALE, ENTITY_SHARED, \
    ENTITY_NOT_SHARED, ENTITY_LEARNED, ENTITY_MARKED, ENTITY_UNMARKED, ENTITY_WATCHED, ENTITY_UNWATCHED, ENTITY_ARCHIVED, ENTITY_UNARCHIVED, \
    EXPOSED_PASSWORD, WEAK_PASSWORD, PRIVILEGE_ESCALATION, PRIVILEGE_DE_ESCALATION, SCORE_ESCALATION, SCORE_DE_ESCALATION, AUTHORIZER_CHANGE, \
    ALERT, NEW_INCIDENT, INCIDENT_TYPE_CHANGE, INCIDENT_SEVERITY_CHANGE, INCIDENT_LIFE_CYCLE_STAGE_CHANGE, POLICY_RULE_MATCH, \
    MFA_SERVICE_ENROLLMENT, LICENSE_CHANGED, SYSTEM_USER_LOGIN, SYSTEM_USER_FAILED_LOGIN, SYSTEM_USER_LOGOUT, SYSTEM_SSH_USER_LOGIN, \
    SYSTEM_SSH_USER_FAILED_LOGIN, SYSTEM_SSH_USER_LOGOUT, SYSTEM_SSH_USER_SESSION_TERMINATION, APPLIANCE_ACTIVATED, APPLIANCE_DEACTIVATED, \
    CONNECTOR_CONFIGURATION_MODIFIED, CONNECTOR_CONFIGURATION_ADDED, CONNECTOR_CONFIGURATION_DELETED, FIREWALL_CONFIGURATION_MODIFIED, \
    POLICY_RULE_MODIFIED, POLICY_RULE_ADDED, POLICY_RULE_DELETED, POLICY_RULES_REORDERED, POLICY_APPLIED, EMAIL_SERVER_CONFIGURATION_MODIFIED, \
    EMAIL_NOTIFICATION_CONFIGURATION_MODIFIED, UPGRADE_INITIATED, SYSTEM_USER_CONFIGURATION_MODIFIED, SYSTEM_USER_CONFIGURATION_ADDED, \
    SYSTEM_USER_CONFIGURATION_DELETED, LOCAL_USER_PASSWORD_CHANGED, SYSTEM_USER_PASSWORD_RESET, SECURITY_CONFIGURATION_MODIFIED, \
    CERTIFICATE_CONFIGURATION_MODIFIED, CERTIFICATE_CONFIGURATION_ADDED, CERTIFICATE_CONFIGURATION_DELETED, EXTERNAL_API_INTEGRATION_STATUS_CHANGED, \
    API_TOKEN_ADDED, API_TOKEN_DELETED, LICENSE_PENDING_EXPIRATION, LICENSE_EXPIRING, LICENSE_EXPIRED, UNCOVERED_DOMAIN_CONTROLLER, \
    INVALID_DOMAIN_USER_CONFIGURATION, UPDATE_AVAILABLE, APPLIANCE_CONNECTIVITY_FAILURE, INLINE_HEALTH_CHECK_FAILURE, INLINE_INVALID_DNS_RESOLUTION, \
    CLOUD_CONNECTIVITY_FAILURE, CONNECTOR_FAILURE]"

TIMELINE_EVENT_TYPES_LIST = ['SUCCESSFUL_AUTHENTICATION', 'FAILED_AUTHENTICATION', 'SERVICE_ACCESS', 'DCERPC_OPERATION', 'REMOTE_CODE_EXECUTION',
    'FILE_OPERATION', 'LDAP_SEARCH', 'ACCOUNT_CREATED', 'PASSWORD_CHANGE', 'ACCOUNT_NAME_CHANGE', 'DEPARTMENT_CHANGE', 'OU_CHANGE', 'EMAIL_ADDRESS_CHANGE',
    'ACCOUNT_ENABLED', 'ACCOUNT_DISABLED', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'ENTITY_RESURGENCE', 'ENTITY_INACTIVE', 'ENTITY_STALE', 'ENTITY_SHARED',
    'ENTITY_NOT_SHARED', 'ENTITY_LEARNED', 'ENTITY_MARKED', 'ENTITY_UNMARKED', 'ENTITY_WATCHED', 'ENTITY_UNWATCHED', 'ENTITY_ARCHIVED', 'ENTITY_UNARCHIVED',
    'EXPOSED_PASSWORD', 'WEAK_PASSWORD', 'PRIVILEGE_ESCALATION', 'PRIVILEGE_DE_ESCALATION', 'SCORE_ESCALATION', 'SCORE_DE_ESCALATION', 'AUTHORIZER_CHANGE',
    'ALERT', 'NEW_INCIDENT', 'INCIDENT_TYPE_CHANGE', 'INCIDENT_SEVERITY_CHANGE', 'INCIDENT_LIFE_CYCLE_STAGE_CHANGE', 'POLICY_RULE_MATCH',
    'MFA_SERVICE_ENROLLMENT', 'LICENSE_CHANGED', 'SYSTEM_USER_LOGIN', 'SYSTEM_USER_FAILED_LOGIN', 'SYSTEM_USER_LOGOUT', 'SYSTEM_SSH_USER_LOGIN',
    'SYSTEM_SSH_USER_FAILED_LOGIN', 'SYSTEM_SSH_USER_LOGOUT', 'SYSTEM_SSH_USER_SESSION_TERMINATION', 'APPLIANCE_ACTIVATED', 'APPLIANCE_DEACTIVATED',
    'CONNECTOR_CONFIGURATION_MODIFIED', 'CONNECTOR_CONFIGURATION_ADDED', 'CONNECTOR_CONFIGURATION_DELETED', 'FIREWALL_CONFIGURATION_MODIFIED',
    'POLICY_RULE_MODIFIED', 'POLICY_RULE_ADDED', 'POLICY_RULE_DELETED', 'POLICY_RULES_REORDERED', 'POLICY_APPLIED', 'EMAIL_SERVER_CONFIGURATION_MODIFIED',
    'EMAIL_NOTIFICATION_CONFIGURATION_MODIFIED', 'UPGRADE_INITIATED', 'SYSTEM_USER_CONFIGURATION_MODIFIED', 'SYSTEM_USER_CONFIGURATION_ADDED',
    'SYSTEM_USER_CONFIGURATION_DELETED', 'LOCAL_USER_PASSWORD_CHANGED', 'SYSTEM_USER_PASSWORD_RESET', 'SECURITY_CONFIGURATION_MODIFIED',
    'CERTIFICATE_CONFIGURATION_MODIFIED', 'CERTIFICATE_CONFIGURATION_ADDED', 'CERTIFICATE_CONFIGURATION_DELETED', 'EXTERNAL_API_INTEGRATION_STATUS_CHANGED',
    'API_TOKEN_ADDED', 'API_TOKEN_DELETED', 'LICENSE_PENDING_EXPIRATION', 'LICENSE_EXPIRING', 'LICENSE_EXPIRED', 'UNCOVERED_DOMAIN_CONTROLLER',
    'INVALID_DOMAIN_USER_CONFIGURATION', 'UPDATE_AVAILABLE', 'APPLIANCE_CONNECTIVITY_FAILURE', 'INLINE_HEALTH_CHECK_FAILURE', 'INLINE_INVALID_DNS_RESOLUTION',
    'CLOUD_CONNECTIVITY_FAILURE', 'CONNECTOR_FAILURE']

PREEMPT_ERR_FAILURES = "Some incidents had issues during ingestion; see logs for details."
PREEMPT_INVALID_UPDATE_INCIDENT_PARAMS = "At least one of either stage and reason OR comment parameters must be included in action request"
